#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JAR_SOURCE="$SCRIPT_DIR/pkspkms-desktop/target/pkspkms-desktop-0.1.0.jar"
ICON_SOURCE="$SCRIPT_DIR/pkspkms-desktop/src/main/resources/brain-icon.png"

# Defaults
PREFIX="${HOME}/.local"
DO_BUILD=true
DO_UNINSTALL=false

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

error() { echo -e "${RED}Error: $*${NC}" >&2; }
warn()  { echo -e "${YELLOW}Warning: $*${NC}" >&2; }
info()  { echo -e "${GREEN}$*${NC}"; }

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Install or uninstall PKSPKMS.

Options:
  --prefix <dir>   Install to <dir> instead of ~/.local
  --system         Shorthand for --prefix /usr/local
  --no-build       Skip the build step (assume JAR already exists)
  --uninstall      Remove installed files
  --help           Show this message

Examples:
  $(basename "$0")                  # Install to ~/.local
  $(basename "$0") --system       # Install to /usr/local (needs sudo)
  $(basename "$0") --uninstall      # Remove from ~/.local
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)
            shift
            PREFIX="$1"
            ;;
        --system)
            PREFIX="/usr/local"
            ;;
        --no-build)
            DO_BUILD=false
            ;;
        --uninstall)
            DO_UNINSTALL=true
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
    shift
done

BIN_DIR="$PREFIX/bin"
SHARE_DIR="$PREFIX/share/pkspkms"
APP_DIR="$PREFIX/share/applications"
ICON_DIR="$PREFIX/share/icons/hicolor/64x64/apps"

uninstall() {
    info "Uninstalling PKSPKMS from $PREFIX ..."

    local files=(
        "$BIN_DIR/pkspkms"
        "$SHARE_DIR/pkspkms.jar"
        "$APP_DIR/pkspkms.desktop"
        "$ICON_DIR/pkspkms.png"
    )

    for f in "${files[@]}"; do
        if [ -e "$f" ]; then
            rm -f "$f"
            info "  Removed: $f"
        else
            warn "  Not found: $f"
        fi
    done

    # Clean up empty directories
    rmdir "$SHARE_DIR" 2>/dev/null || true

    info "Uninstall complete."
}

if [ "$DO_UNINSTALL" = true ]; then
    uninstall
    exit 0
fi

# Build if needed
if [ ! -f "$JAR_SOURCE" ]; then
    if [ "$DO_BUILD" = true ]; then
        info "Fat JAR not found. Building first..."
        if ! "$SCRIPT_DIR/build.sh"; then
            error "Build failed. Cannot install."
            exit 1
        fi
    else
        error "Fat JAR not found: $JAR_SOURCE"
        error "Run ./build.sh first, or omit --no-build."
        exit 1
    fi
fi

info "Installing PKSPKMS to $PREFIX ..."

# Create directories
mkdir -p "$BIN_DIR" "$SHARE_DIR" "$APP_DIR" "$ICON_DIR"

# Install JAR
cp "$JAR_SOURCE" "$SHARE_DIR/pkspkms.jar"
info "  Installed: $SHARE_DIR/pkspkms.jar"

# Install icon
cp "$ICON_SOURCE" "$ICON_DIR/pkspkms.png"
info "  Installed: $ICON_DIR/pkspkms.png"

# Create wrapper script
cat > "$BIN_DIR/pkspkms" <<EOF
#!/usr/bin/env bash
# PKSPKMS wrapper — auto-generated by install.sh
set -e
exec java -jar "$SHARE_DIR/pkspkms.jar" "\$@"
EOF
chmod +x "$BIN_DIR/pkspkms"
info "  Installed: $BIN_DIR/pkspkms"

# Create .desktop entry
cat > "$APP_DIR/pkspkms.desktop" <<EOF
[Desktop Entry]
Name=PKSPKMS
Comment=PK's Personal Knowledge Management Software
Exec=pkspkms server --tray
Icon=pkspkms
Type=Application
Categories=Utility;Office;
Terminal=false
EOF
info "  Installed: $APP_DIR/pkspkms.desktop"

info ""
info "Installation complete!"
info ""

# PATH check
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    warn "$BIN_DIR is not on your PATH."
    warn "Add this to your shell profile (e.g. ~/.bashrc or ~/.zshrc):"
    warn "  export PATH=\"$BIN_DIR:\$PATH\""
    info ""
fi

# Desktop database update hint
if command -v update-desktop-database &>/dev/null; then
    info "You may want to refresh the application menu:"
    info "  update-desktop-database $APP_DIR"
    info ""
fi

info "Run PKSPKMS:"
info "  pkspkms server --directory <vault> --port 3000"
info "  pkspkms server --directory <vault> --port 3000 --tray"
info ""
info "Or launch from your desktop's application menu (tray mode)."
