#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout -pl pkspkms-desktop 2>/dev/null || echo 0.1.0)"
JAR_SOURCE="$SCRIPT_DIR/pkspkms-desktop/target/pkspkms-desktop-${VERSION}.jar"

# Defaults
PREFIX="${HOME}/.local"
DO_BUILD=true
DO_UNINSTALL=false

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

error() { echo -e "${RED}Error: $*${NC}" >&2; }
warn()  { echo -e "${YELLOW}Warning: $*${NC}" >&2; }
info()  { echo -e "${GREEN}$*${NC}"; }

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Install or uninstall PKSPKMS.

Options:
  --prefix <dir>   Install to <dir> instead of ~/.local
  --system         Shorthand for --prefix /usr/local
  --no-build       Skip the build step (assume JAR already exists)
  --uninstall      Remove installed files
  --help           Show this message

Examples:
  $(basename "$0")                  # Install to ~/.local
  $(basename "$0") --system       # Install to /usr/local (needs sudo)
  $(basename "$0") --uninstall      # Remove from ~/.local
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)
            shift
            PREFIX="$1"
            ;;
        --system)
            PREFIX="/usr/local"
            ;;
        --no-build)
            DO_BUILD=false
            ;;
        --uninstall)
            DO_UNINSTALL=true
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
    shift
done

BIN_DIR="$PREFIX/bin"
SHARE_DIR="$PREFIX/share/pkspkms"

uninstall() {
    info "Uninstalling PKSPKMS from $PREFIX ..."

    local files=(
        "$BIN_DIR/pkspkms"
        "$SHARE_DIR/pkspkms.jar"
    )

    for f in "${files[@]}"; do
        if [ -e "$f" ]; then
            rm -f "$f"
            info "  Removed: $f"
        else
            warn "  Not found: $f"
        fi
    done

    # Clean up empty directories
    rmdir "$SHARE_DIR" 2>/dev/null || true

    info "Uninstall complete."
}

if [ "$DO_UNINSTALL" = true ]; then
    uninstall
    exit 0
fi

# Build if needed
if [ ! -f "$JAR_SOURCE" ]; then
    if [ "$DO_BUILD" = true ]; then
        info "Fat JAR not found. Building first..."
        if ! "$SCRIPT_DIR/build.sh"; then
            error "Build failed. Cannot install."
            exit 1
        fi
    else
        error "Fat JAR not found: $JAR_SOURCE"
        error "Run ./build.sh first, or omit --no-build."
        exit 1
    fi
fi

info "Installing PKSPKMS to $PREFIX ..."

# Create directories
mkdir -p "$BIN_DIR" "$SHARE_DIR"

# Install JAR
cp "$JAR_SOURCE" "$SHARE_DIR/pkspkms.jar"
info "  Installed: $SHARE_DIR/pkspkms.jar"

# Create wrapper script
cat > "$BIN_DIR/pkspkms" <<EOF
#!/usr/bin/env bash
# PKSPKMS wrapper — auto-generated by install.sh
set -e
exec java -XX:+UseSerialGC -jar "$SHARE_DIR/pkspkms.jar" "\$@"
EOF
chmod +x "$BIN_DIR/pkspkms"
info "  Installed: $BIN_DIR/pkspkms"

info ""
info "Installation complete!"
info ""

# PATH check
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    warn "$BIN_DIR is not on your PATH."
    warn "Add this to your shell profile (e.g. ~/.bashrc or ~/.zshrc):"
    warn "  export PATH=\"$BIN_DIR:\$PATH\""
    info ""
fi

info "Run PKSPKMS:"
info "  pkspkms server --directory <vault> --port 3000"
info "  pkspkms server --directory <vault> --port 3000 --tray"
info ""
info "First server start writes an API token to ~/.config/pkspkms/token (0600)."
info "Send it as: Authorization: Bearer $(cat ~/.config/pkspkms/token)"
